# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bb00dfd01bf5d3f8d77bc2fdc7fd28ee0816af90f216c1e6a08ac8c8a68a161d2a09910a09e970995c734cd316aa89f44a2da85f936f088e08f48c74de3d8e6

test:
  secret_key_base: 4958da39b8b3ebef4bcf964bc9679c82b2d926e6e5a03176139dbfbc7493b96c8cc93263f1c3e145c7bdffcd1d6627abe2e68aa8a8b50f67294f0e73a774edc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
